apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: ph-gen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: nginx-config-volume
          configMap:
            name: frontend-nginx-config-volume
      containers:
      - image: vinipilan/ph-gen-app:dev-frontend-latest
        name: app
        resources:
          requests:
            memory: 100Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
