apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: ph-gen-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: frontend
  type: ClusterIP
