apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: ph-gen-app
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
  selector:
    app: backend
  type: ClusterIP
