apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: ph-gen-app
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: database
  type: ClusterIP
