apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: ph-gen-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: adminer
  type: ClusterIP
