# Docker compose file used to create the dev environment
services:
  ph-gen-app-cache:
    image: bitnami/keydb:latest
    container_name: ph-gen-app-cache
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    # ports:
    #   - "6379:6379"
    volumes:
      - keydb-data:/data
  ph-gen-app-database:
    image: postgres:16-alpine
    container_name: ph-gen-app-database
    environment:
      POSTGRES_DB: ph-gen-db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 123
    # ports:
    #   - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  ph-gen-app-database-adminer:
    container_name: ph-gen-app-database-adminer
    image: adminer:latest
    ports:
      - "8081:8080"

  ph-gen-app-frontend:
    container_name: ph-gen-app-frontend
    build:
      context: "frontend"
      dockerfile: "Dockerfile"
    ports:
    - "8080:80"
    volumes:
    - ./frontend/nginx-files:/etc/nginx/conf.d
    - ./frontend/html:/usr/share/nginx/html/test

  ph-gen-app-backend:
    container_name: ph-gen-app-backend
    build:
      context: "backend"
      dockerfile: "Dockerfile"
    volumes:
    - ./backend/api:/home/ph-gen-app
    # ports:
    # - "8082:8000"

volumes:
  keydb-data:
  pg-data:
