# Ref: https://github.com/marketplace/actions/build-and-push-docker-images

name: Build dev project

on: 
  # pull_request:
  #   types: [closed]
  #   branch: ["DEV"]
  workflow_dispatch:
    inputs:
      path:
        description: "Diretório do projeto (exige Dockerfile na raíz)"
        required: true
        type: string
      module:
        description: "Nome do módulo"
        required: true
        type: string
  
jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
    # - name: prepare
    #   run: |
    #     echo "$project={{ inputs.path }}" > $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.path }}
        push: true
        tags: vinipilan/ph-gen-app:dev-${{ inputs.module }}-${{ GITHUB_SHA::5 }}
